"""initial_migration

Revision ID: f01e96a84b56
Revises: 
Create Date: 2026-04-07 23:01:52.406458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f01e96a84b56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('senha', sa.String(length=255), nullable=True),
    sa.Column('cadastro_completo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)

    op.create_table('comercios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_comercio', sa.String(length=120), nullable=False),
    sa.Column('segmento', sa.String(length=80), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('telefone')
    )
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('unidade', sa.String(length=50), nullable=True),
    sa.Column('data_validade', sa.Date(), nullable=False),
    sa.Column('comercio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comercio_id'], ['comercios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produtos_comercio_id'), ['comercio_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produtos_comercio_id'))

    op.drop_table('produtos')
    op.drop_table('comercios')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    # ### end Alembic commands ###
